language: python
python:
  - "3.5"

# command to install dependencies
install:
    - pip3 install slack
    - pip3 install feedparser
    - pip3 install mysql-connector-python-rf

notifications:
    email: false

script: nosetests